apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
  labels:
    name: locust-worker
spec:
  replicas: 5
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      containers:
        - name: locust-worker
          image: locustio/locust:1.5.2
          command: [ "locust" ]
          args: ["--worker", "--master-host", "$(LOCUST_MASTER)"]
          volumeMounts:
            - mountPath: /home/locust
              name: locust-scripts
          resources:
            requests:
              memory: "1G"
              cpu: "1"
            limits:
              memory: "1.5G"
              cpu: "1.2"
          env:
            - name: LOCUST_MASTER
              value: locust-service
            - name: LOCUSTFILE_PATH
              value: /locust/locustfile.py
      volumes:
        - name: locust-scripts
          configMap:
            name: scripts